import '../css/globals.css';

import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import React from 'react';

import { Providers } from '@/services';

const inter = Roboto({
	weight: ['100', '300', '400', '500', '700', '900'],
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
  children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<Providers>
				<body className={inter.className}>{children}</body>
			</Providers>
		</html>
	);
}
