version: '3.9'

services:
  db:
    container_name: db_delivery
    image: postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - 5432:5432
  api:
    container_name: delivery_api
    image: node:20-alpine
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000